# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

newIssueWelcomeComment: >
  Thanks for opening your first issue here! ğŸ‰ Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted on PRs from first-time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! ğŸš€ Please check out our contributing guidelines in the [CONTRIBUTING.md](/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted on pull requests merged by a first-time user
firstPRMergeComment: >
  ğŸ‰ Congrats on merging your first pull request! We here at Web Componentify are super proud of you! ğŸš€ğŸ‘
